package com.nightshift.model.entity;

import com.nightshift.model.enums.PatchStatus;
import com.nightshift.model.enums.VerifierVerdict;
import com.nightshift.util.UuidV7Util;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * A unified-diff patch generated by the Fix agent for a specific incident.
 */
@Entity
@Table(name = "patch_proposal")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PatchProposal {

    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "incident_id", nullable = false)
    private Incident incident;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 24)
    private PatchStatus status;

    @Column(name = "unified_diff", columnDefinition = "text")
    private String unifiedDiff;

    @Column(name = "rationale", columnDefinition = "text")
    private String rationale;

    @Column(name = "test_plan", columnDefinition = "text")
    private String testPlan;

    @Column(name = "files_changed", nullable = false)
    @Builder.Default
    private int filesChanged = 0;

    @Column(name = "lines_added", nullable = false)
    @Builder.Default
    private int linesAdded = 0;

    @Column(name = "lines_removed", nullable = false)
    @Builder.Default
    private int linesRemoved = 0;

    @Column(name = "provider", length = 32)
    private String provider;

    @Column(name = "model", length = 64)
    private String model;

    @Enumerated(EnumType.STRING)
    @Column(name = "verifier_verdict", length = 16)
    private VerifierVerdict verifierVerdict;

    @Column(name = "verifier_notes", columnDefinition = "text")
    private String verifierNotes;

    @Column(name = "rejection_code", length = 48)
    private String rejectionCode;

    @Column(name = "attempt", nullable = false)
    @Builder.Default
    private int attempt = 1;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    void assignId() {
        if (id == null) {
            id = UuidV7Util.create();
        }
    }
}
