package com.nightshift.util;

import com.nightshift.model.entity.Incident;
import com.nightshift.model.entity.PatchProposal;
import com.nightshift.model.entity.ScanRun;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Renders the GitHub Pull Request body using {@code docs/PR_TEMPLATE.md}
 * populated with incident, triage, and patch proposal data.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class PrBodyRenderer {

    private static final String DEFAULT_TEMPLATE = """
            # [Nightshift] ${TITLE}

            ## 1. What is wrong
            ${ONE_SENTENCE_SUMMARY}

            ## 2. Severity
            **${SEVERITY}** — ${SEVERITY_RATIONALE}
            - **Frequency:** Observed ${OCCURRENCE_COUNT} times between ${FIRST_SEEN} and ${LAST_SEEN}.
            - **Affected Service:** `${SERVICE_NAME}`

            ## 3. Why it happens (Root Cause)
            ${ROOT_CAUSE}

            ## 4. What it costs if we do not fix it now
            ${FUTURE_IMPACT}

            ## 5. Evidence
            ```text
            ${EVIDENCE}
            ```

            ## 6. The fix
            ${FIX_RATIONALE}

            ```diff
            ${UNIFIED_DIFF}
            ```

            ## 7. How to verify
            ${TEST_PLAN}

            ## 8. Provenance
            - **Provider / Model:** ${PROVIDER} / ${MODEL}
            - **Scan Run ID:** `${SCAN_RUN_ID}`
            - **Generated by:** Nightshift Automated Triage & Remediation Pipeline
            - *Reviewed by nobody yet. Please inspect before merging.*
            """;

    private final SecretMasker secretMasker;

    /**
     * Renders the PR markdown body.
     */
    public String render(Incident incident, PatchProposal proposal, ScanRun scanRun) {
        String template = loadTemplate();

        String title = nullSafe(incident.getTitle(), "Automated incident fix");
        String summary = title;
        if (summary.contains(".")) {
            summary = summary.substring(0, summary.indexOf('.') + 1);
        }

        String evidence = incident.getSampleMessage() != null
                ? secretMasker.mask(incident.getSampleMessage())
                : (incident.getNormalizedMessage() != null ? secretMasker.mask(incident.getNormalizedMessage()) : "No raw evidence available.");

        if (incident.getSampleStacktrace() != null && !incident.getSampleStacktrace().isBlank()) {
            evidence += "\n\n" + secretMasker.mask(incident.getSampleStacktrace());
        }

        return template
                .replace("${TITLE}", title)
                .replace("${ONE_SENTENCE_SUMMARY}", summary)
                .replace("${SEVERITY}", incident.getSeverity() != null ? incident.getSeverity().name() : "MAJOR")
                .replace("${SEVERITY_RATIONALE}", nullSafe(incident.getSeverityRationale(), "Identified during automated scan."))
                .replace("${OCCURRENCE_COUNT}", String.valueOf(incident.getOccurrenceCount()))
                .replace("${FIRST_SEEN}", incident.getFirstSeenAt() != null ? incident.getFirstSeenAt().toString() : "N/A")
                .replace("${LAST_SEEN}", incident.getLastSeenAt() != null ? incident.getLastSeenAt().toString() : "N/A")
                .replace("${SERVICE_NAME}", nullSafe(incident.getServiceName(), "unknown-service"))
                .replace("${ROOT_CAUSE}", nullSafe(incident.getRootCause(), "See diagnosis in incident details."))
                .replace("${FUTURE_IMPACT}", nullSafe(incident.getFutureImpact(), "Unchecked resource degradation or runtime exceptions."))
                .replace("${EVIDENCE}", evidence)
                .replace("${FIX_RATIONALE}", nullSafe(proposal.getRationale(), "Resolves identified defect."))
                .replace("${UNIFIED_DIFF}", nullSafe(proposal.getUnifiedDiff(), ""))
                .replace("${TEST_PLAN}", nullSafe(proposal.getTestPlan(), "Execute existing automated tests."))
                .replace("${PROVIDER}", nullSafe(proposal.getProvider(), "heuristic"))
                .replace("${MODEL}", nullSafe(proposal.getModel(), "rule-based"))
                .replace("${SCAN_RUN_ID}", scanRun != null && scanRun.getId() != null ? scanRun.getId().toString() : "standalone");
    }

    private String loadTemplate() {
        Path p = Path.of("docs/PR_TEMPLATE.md");
        if (Files.exists(p)) {
            try {
                return Files.readString(p, StandardCharsets.UTF_8);
            } catch (IOException e) {
                log.warn("Could not read docs/PR_TEMPLATE.md: {}", e.getMessage());
            }
        }
        return DEFAULT_TEMPLATE;
    }

    private static String nullSafe(String s, String def) {
        return (s != null && !s.isBlank()) ? s : def;
    }
}